### ISSUE TITLE
`golem-client` on `wasm32-wasip2` target troubles

### ISSUE THREAD

**Issue by smndtrl** [golemcloud/golem#1073]
Hi,

I'm trying to invoke a worker from our serverless functions and using reqwest via REST with typed json is a bit cumbersome. I looked into using your generated `golem-client` but due to its dependency on `golem-common` it pulls in a lot of crates that don't compile on `wasm32-wasip2` that maybe don't need to be there for an API client to work like `wasmtime` or `cranelift-codegen`.
I may also just have misunderstood what `golem-client`s purpose is.

```
wasmtime v21.0.1
├── golem-wasm-rpc v1.0.7
│   ├── golem-api-grpc v1.0.26
│   │   ├── golem-common v1.0.26
│   │   │   └── golem-client v1.0.26
```

**Comment by vigoo** [comment]
That's true, we should introduce features into `golem-common` so those parts become optional. The generated client code only depends on this crate to share some of the model types instead of "regenerating" them.
