### ISSUE TITLE
Clean up the test architecture in golem-cli tests

### ISSUE THREAD

**Issue by afsalthaj** [golemcloud/golem#1121]
I think there is over use of DRY in cli tests that we should be avoiding. It's hard to understand, at least in api definition and deployment side.

cc @nicoburniske

**Comment by vigoo** [comment]
This should be more specific - it's not clear what do you refere to

**Comment by vigoo** [comment]
Closing as not specific enough. We will do our best to improve code quality if we touch CLI tests.
