### ISSUE TITLE
Make sure to support all of the terms in ConstructorPattern in Expr

### ISSUE THREAD

**Issue by vigoo** [golemcloud/golem#193]

**Comment by afsalthaj** [comment]
The reason for 3-4 days here is, it may end up in shuffling a bit of code, some cleanups and writing tests. I may have over estimated. But I am keeping it to be 5

**Comment by afsalthaj** [comment]
Expecting only 2 days, but giving it estimate of 5 making it 3 or 4 days, to give a space for cleanup and necessary refactoring and writing proper tests
