### ISSUE TITLE
Make sure to support javascript style map look ups for SelectField

### ISSUE THREAD

**Issue by vigoo** [golemcloud/golem#220]
Based on discussion with @jdegoes , users should be allowed to do the following:

```
worker-name: my-worker-name${request.header["user"]}
```

As well as

```
worker-name: my-worker-name${request.header.user}
```

**Comment by afsalthaj** [comment]
Untagged from milestone 1.0, as it won't contribute significantly to what we want to achieve in milestone 1.0
