### ISSUE TITLE
Run benchmarks in CI

### ISSUE THREAD

**Issue by vigoo** [golemcloud/golem#507]
The benchmarks should be executed in CI so we continuously see any performance regressions.

Ideas/nice to have:
- trigger it on-demand in PRs (so we don't run all the time only when we think our change might have performance effects)
- report result in the PR as comments
- figure out a nice way to show results
- should show diff to some baseline

**Comment by afsalthaj** [comment]
I think I covered all of it for now:
https://github.com/golemcloud/golem/pull/545#issue-2333689262
