### ISSUE TITLE
Adding workers while cache compile is running after component update results in timeouts / stuck workers

### ISSUE THREAD

**Issue by noise64** [golemcloud/golem#548]
Steps for repro:
- use a wasm source for the component that requires a long compilation time (more then 1 minute)
- update the component
- while compilation cache is still being built add a new worker

The last step many times results in timeouts, and if so then:
- the added worker seems to be idle, but cannot be invoked, invocations also result in timeouts
- no new worker can be added, doing so also resulting in timeouts

In the logs no WARN or ERRORs are visible apart from the request timeouts.

**Comment by vigoo** [comment]
I believe this was fixed by moving the component compilation to the invocation loop from the place where it was holding the (previously) `running` mutex in `Worker`
