### ISSUE TITLE
Latest TinyGo fails to run our http test

### ISSUE THREAD

**Issue by vigoo** [golemcloud/golem#709]

**Comment by vigoo** [comment]
The `tinygo-wasi-http` test component recompiled with TinyGo 0.32 fails with:

```
trace:
    0: 0x3574a - runtime.abort
                    at /opt/homebrew/Cellar/tinygo/0.32.0/src/runtime/runtime_tinygowasm.go:70:6              - runtime.runtimePanicAt
                    at /opt/homebrew/Cellar/tinygo/0.32.0/src/runtime/panic.go:87:7
    1: 0x783a - runtime.nilPanic
                    at /opt/homebrew/Cellar/tinygo/0.32.0/src/runtime/panic.go:150:16
    2: 0x80b0c - main!(*net/http.Client).Post
    3: 0x7b1df - tinygo_wasi_example1
                    at /opt/homebrew/Cellar/tinygo/0.32.0/src/net/http/client.go:461:27
    4: 0x9482e - __wasm_export_tinygo_wasi_example1
                    at /Users/vigoo/projects/ziverge/golem-services/test-components/tinygo-wasi-http/tinygo_wasi/tinygo_wasi.c:5228:3

Caused by:
    wasm trap: wasm `unreachable` instruction executed
```

Try to investigate and fix it. If it is not possible, the (new) Go Language Guide must specify the older TinyGo version to use.

**Comment by vigoo** [comment]
The test case is `guest_languages::tinygo_http_client`, which is not temporarily ignored

**Comment by noise64** [comment]
The current custom net/http implementation does not use the RoundTripper, so our custom implementation is not called at all.

See: https://github.com/tinygo-org/net/blob/a79417481d37e21f29d257c28fecc503df9703e0/http/client.go#L159

There is an already merged PR that fixes this in the net repo: https://github.com/tinygo-org/net/pull/32
And it was also bumped in the main tinygo repo https://github.com/tinygo-org/tinygo/pull/4351

So when there will be a new release, it should work with that.
