### ISSUE TITLE
Plan an SQLite implementation of the BlobStorage trait

### ISSUE THREAD

**Issue by vigoo** [golemcloud/golem#855]
Examine the interface `BlobStorage` and figure out the exact SQLite queries necessary for each function of the trait. 

This is a preparation step before actually writing the implementation. Document the plan as a comment of this issue. Make sure to also plan the SQLite statements required to initialize the database (create tables but only if does not exists, etc). The trait implementation will have to run these if needed so can be transparently used in place of the other implementations.

**Comment by irach-ramos** [comment]
# BlobStorage in Sqlite

# Table definition

| Blob storage table |
| :---- |
|  CREATE TABLE IF NOT EXISTS blob\_storage (    <br/> &nbsp;&nbsp; namespace TEXT NOT NULL,                \-- 'Bucket' or namespace     <br/> &nbsp;&nbsp; path TEXT NOT NULL,                            \-- Full path or index within the namespace    <br/>  &nbsp;&nbsp; data BLOB,                                              \-- The actual blob data     <br/>  &nbsp;&nbsp; last\_modified\_at TIMESTAMP DEFAULT CURRENT\_TIMESTAMP, \-- Metadata: Last modified timestamp    <br/> &nbsp;&nbsp;  size INTEGER NOT NULL,                     \-- Metadata: Size of the blob     <br/> &nbsp;&nbsp; is\_directory BOOLEAN DEFAULT FALSE NOT NULL,   \-- Flag indicating if the row represents a directory     <br/> &nbsp;&nbsp; PRIMARY KEY (namespace, path)         \-- Composite primary key <br/> );  |

# Queries by function

| trait function | statement |
| ----- | ----- |
| get\_raw  | SELECT data FROM blob\_storage WHERE namespace \= ?  AND path \= ?  AND is\_directory \= FALSE; |
| get\_metadata  | SELECT last\_modified\_at, size FROM blob\_storage WHERE namespace \= ? AND path \= ?;  |
| put\_raw | INSERT INTO blob_storage (namespace, path, data, size, is_directory) VALUES (?, ?, ?, ?, FALSE) ON CONFLICT(namespace, path) DO UPDATE SET data = excluded.data, size = excluded.size, last_modified_at = CURRENT_TIMESTAMP;  |
| delete | DELETE FROM blob\_storage WHERE namespace \= ?  AND path \= ?; |
| create\_dir | INSERT INTO blob\_storage (namespace, path, data, size, is\_directory) VALUES (?, ?, NULL, 0, TRUE) ON CONFLICT(namespace, path) DO UPDATE SET is\_directory \= TRUE, data \= NULL, size \= 0; |
| list\_dir | SELECT path FROM blob\_storage WHERE namespace \= ? AND path LIKE ? AND is\_directory \= FALSE; |
| delete\_dir | DELETE FROM blob\_storage WHERE namespace \= ?  AND path LIKE ?'; |
| exists | SELECT 1 FROM blob\_storage WHERE namespace \= ? AND path \= ? LIMIT 1; |
