### ISSUE TITLE
Plan an SQLite implementation of the KeyValueStorage trait 

### ISSUE THREAD

**Issue by vigoo** [golemcloud/golem#856]
Examine the interface KeyValueStorage and figure out the exact SQLite queries necessary for each function of the trait.

This is a preparation step before actually writing the implementation. Document the plan as a comment of this issue. Make sure to also plan the SQLite statements required to initialize the database (create tables but only if does not exists, etc). The trait implementation will have to run these if needed so can be transparently used in place of the other implementations.

**Comment by irach-ramos** [comment]
I attached a docx document and added the md description of the plan KeyValueStorage in Sqlite

# Table definitions

| Key value storage table |
| :---- |
| CREATE TABLE IF NOT EXISTS kv\_storage (                 id INTEGER PRIMARY KEY AUTOINCREMENT,                 key TEXT NOT NULL,                \-- The key to store                 value BLOB NOT NULL,            \-- The value to store                 namespace TEXT NOT NULL,   – The namespace of  the key value                  UNIQUE(key, namespace)         \-- Avoid duplicate key values in a namespace             )  |

| Set storage storage table |
| :---- |
| CREATE TABLE IF NOT EXISTS set\_storage (             id INTEGER PRIMARY KEY AUTOINCREMENT,             key TEXT NOT NULL,                  \-- The set's key             value BLOB NOT NULL,               \-- The value (element)             namespace TEXT NOT NULL,      – The namespace of  the key value              UNIQUE(key,value, namespace)   \-- Ensure uniqueness of values per (set, namespace)         )  |

| Sorted set storage table |
| :---- |
| CREATE TABLE IF NOT EXISTS sorted\_set\_storage (             id INTEGER PRIMARY KEY AUTOINCREMENT,             key TEXT NOT NULL,                    \-- The sorted set's key             value BLOB NOT NULL,                \-- The value (element)             namespace TEXT NOT NULL,       – The namespace of  the key value              score REAL NOT NULL,                 \-- The score associated with the value             UNIQUE(key, value, namespace)   \-- Ensure uniqueness of values per (set, namespace)         )  |

# Queries by function

| trait function | Sqlite Table | statement |
| ----- | ----- | ----- |
| set  | kv\_storage | INSERT OR REPLACE INTO kv\_storage (key, value, namespace) VALUES ('key', 'value',’NS’); |
| set\_many  | kv\_storage | INSERT OR REPLACE INTO kv\_storage (key, value, namespace) VALUES ('key1', 'value1',’NS’),('key2', 'value2',’NS’),('key3', 'value3',’NS’); |
| set\_if\_not\_exists | kv\_storage | INSERT OR IGNORE INTO kv\_storage (key, value, namespace) VALUES ('key', 'value',’NS’); |
| get | kv\_storage | SELECT value from kv\_storage where key \= ‘key’ and namespace=’NS’ ; |
| get\_many | kv\_storage | SELECT key, value FROM kv\_storage WHERE key IN ('key1', 'key2', 'key3') AND namespace \= ’NS’; |
| del | kv\_storage | DELETE FROM kv\_storage where key \= ‘key and namespace=’NS’’; |
| del\_many | kv\_storage | DELETE FROM kv\_storage WHERE key IN ('key1', 'key2', 'key3') AND namespace \= ’NS’; |
| exists | kv\_storage | SELECT 1 FROM kv\_storage where key \= ‘key’ AND namespace=’NS’; |
| keys | kv\_storage | SELECT key FROM kv\_storage WHERE namespace=’NS’; |
| add\_to\_set | set\_storage | INSERT OR IGNORE INTO set\_storage (key, value,namespace) VALUES ('key1', 'value1', ‘NS’); |
| remove\_from\_set | set\_storage | DELETE FROM set\_storage WHERE key \= ‘key and namespace=’NS’’; |
| members\_of\_set | set\_storage | SELECT value from set\_storage WHERE key \= ‘key’ and namespace=’NS’ ; |
| add\_to\_sorted\_set | sorted\_set\_storage | INSERT INTO sorted\_set\_storage (key, value, namespace, score) VALUES ('key1', 'value1','NS', 1.0)              ON CONFLICT(key, value, namespace) DO UPDATE SET score \= excluded.score; |
| remove\_from\_sorted\_set | sorted\_set\_storage | DELETE FROM sorted\_set\_storage WHERE key \= ‘key’ AND namespace=’NS’; |
| get\_sorted\_set | sorted\_set\_storage | SELECT value, score FROM sorted\_set\_storage WHERE key \= 'key' AND namespace \= 'NS' ORDER BY score ASC; |
| query\_sorted\_set | sorted\_set\_storage | SELECT value, score FROM sorted\_set\_storage WHERE key \= 'key' AND namespace \= 'NS' AND score BETWEEN 1.0 AND 10.0 ORDER BY score ASC; |

[KeyValueStorage in Sqlite.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEN4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fba8a7ee780ba1deccaa8afde929d8c0277f1f5b/KeyValueStorage%20in%20Sqlite.docx)

**Comment by jdegoes** [comment]
Why store `id` for the set and sorted set tables? It won't be used because you already have `key`. 

You also need a (composite) primary key constraint on `key` / `namespace`. 

Furthermore, you definitely need an index on the composite keys, as well as `score`, since otherwise sorting will be extremely slow.

**Comment by irach-ramos** [comment]
Thank you John, I updated the schema definition. (in the comment and attached)
Please have a look.

[KeyValueStorage in Sqlite.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2EwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dcf27a0a3379c4e3ed5dc7880928d7a89db35bcb/KeyValueStorage%20in%20Sqlite.docx)
