### ISSUE TITLE
Plan an SQLite implementation of the IndexedStorage trait

### ISSUE THREAD

**Issue by vigoo** [golemcloud/golem#857]
Examine the interface IndexedStorage and figure out the exact SQLite queries necessary for each function of the trait.

This is a preparation step before actually writing the implementation. Document the plan as a comment of this issue. Make sure to also plan the SQLite statements required to initialize the database (create tables but only if does not exists, etc). The trait implementation will have to run these if needed so can be transparently used in place of the other implementations.

**Comment by irach-ramos** [comment]
# IndexedStorage in Sqlite

# Table definitions

| index storage table |
| :---- |
|  CREATE TABLE IF NOT EXISTS index\_storage (   <br/>&nbsp;&nbsp;&nbsp;namespace TEXT NOT NULL,            \-- Namespace to logically group entries   <br/>&nbsp;&nbsp;&nbsp; key TEXT NOT NULL,                         \-- Unique identifier for the index   <br/> &nbsp;&nbsp;&nbsp;id INTEGER NOT NULL,                     \-- Unique numeric identifier for each entry   <br/>&nbsp;&nbsp;&nbsp; value BLOB NOT NULL,                     \-- Arbitrary binary payload for each entry   <br/> &nbsp;&nbsp;&nbsp;PRIMARY KEY (namespace, key, id)  \-- Unique constraint on (namespace, key, id) <br/>); <br/><br/>&nbsp;&nbsp;CREATE INDEX IF NOT EXISTS idx\_key ON index\_storage (namespace, key); |

# Queries by function

| trait function | statement |
| ----- | ----- |
| number\_of\_replicas  | Always 1 |
| wait\_for\_replicas  | Always 1 |
| exists | `SELECT EXISTS(SELECT 1 FROM index_storage WHERE namespace = ? AND key = ?);`  |
| scan | SELECT key FROM index\_storage WHERE namespace \= ? AND key LIKE ? ORDER BY key LIMIT ? OFFSET ?; |
| append | INSERT INTO index\_storage (namespace, key, id, value) VALUES (?,?,?,?); |
| length | SELECT COUNT(\*) FROM index\_storage WHERE namespace \= ? AND key \= ?; |
| delete | DELETE FROM index\_storage WHERE namespace \= ? AND key \= ?; |
| read | SELECT id, value FROM storage WHERE namespace \= ? AND key \= ? AND id BETWEEN ? AND ? |
| first | SELECT id, value FROM index\_storage WHERE namespace \= ? AND key \= ? ORDER BY id ASC LIMIT 1; |
| last | SELECT id, value FROM index\_storage WHERE namespace \= ? AND key \= ? ORDER BY id DESC LIMIT 1; |
| closest | SELECT id, value FROM index\_storage WHERE namespace \= ? AND key \= ? AND id \<= ? ORDER BY id DESC LIMIT 1; |
| drop\_prefix | DELETE FROM index\_storage WHERE namespace \= ? AND key \= ? AND id \<= ?; |

#
