### ISSUE TITLE
Rib Robustness: Make sure Rib doesn't condsider random variables as global variables

### ISSUE THREAD

**Issue by afsalthaj** [golemcloud/golem#881]

**Comment by jdegoes** [comment]
Shouldn't ordinary type-checking provide this? We know that request may contain `path`, `headers`, `body`, so really the only thing we don't know, initially, is `body`. Once we learn 'body', if we back-propagate that, and combine it with the other types we know, won't we have a complete picture of the type of `request`?

**Comment by afsalthaj** [comment]
@jdegoes  I was more of talking about tagging any variable as global input. At `golem-rib` side, anything that's not declared is turning out to be a gobal variable. Example



```
 let my_record = request.path;
 let result = foo-function(my_record);
 match result {
    some(_) => "success"
    none => msg
 }


```


The global input requirement for the above script is a request record

```
"request" -> Record("path" -> Record ("user -> Str) )
"msg" -> Str
```

**Comment by afsalthaj** [comment]
@jdegoes  Yes Rib is now providing the complete type information of a "request" and is sent back to UI. Example: After compilation Rib returns The `RibInputTypeInfo` (the input requirements as something like below)

```
"request" -> 
    Record(
     "path" -> Record ("user -> Str) , 
     "body" -> Record("employee" -> Record("id" -> Str, "name" -> Str)
   )

```
