### ISSUE TITLE
Rib Robustness: Remove support of out interpolations from Rib Syntax

### ISSUE THREAD

**Issue by afsalthaj** [golemcloud/golem#892]
The original description of this ticket was testing a specific syntax for which type inference failed.
However, after investigating more, we found that type_inference was actually correct and the issue was related to parser,
where it tries to incorporate the support of interpolations at the outer level.

As part of this ticket, we need to ensure we remove the support of outer interpolations from Rib Grammar, and remove any hacks around it.

Make sure we have backward compatibility with the help of tests, to support those older expressions that may be wrapped in `${..}`. This goes for both persistent layer as well as API layer. Make sure these extra fuctions are well commented, that it is only to support backward compatibility.

Update the existing tests to focus on un-interpolated expressions for better maintainability.

**Comment by jdegoes** [comment]
There might be doc updates required here.
