### ISSUE TITLE
List comprehension support in Rib

### ISSUE THREAD

**Issue by vigoo** [golemcloud/golem#909]
Support list/stream comprehensions, which enable “mapping” and “flatMapping” data inside lists.
    
    ```
    let ages = 
      for p in people {
        yield p.age;
      };
    ```

**Comment by afsalthaj** [comment]
```
let ages = 
  for p in people {
     let z = p.age + 1;
     z
  };
```

**Comment by afsalthaj** [comment]
https://app.zenhub.com/workspaces/golem-cloud-65f5b68988aba80f7d690199/issues/gh/golemcloud/golem/1042
