### ISSUE TITLE
Revoking shards on worker executor is not interrupting running workers

### ISSUE THREAD

**Issue by vigoo** [golemcloud/golem#957]
All running workers belonging to the shards being revoked should be interrupted, and the revoke request handler can only return when all of them has been unloaded, otherwise the shards got assigned to an other executor too soon.

**Comment by SAMBILI** [comment]
download
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by vigoo** [comment]
This already works as expected, false alarm
